name: mac

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v2

    - name: Setting the environment up.
      env:
        VNC_USER_PASSWORD: "root"
        VNC_PASSWORD: "root"
      run: |
        source configure.sh "$VNC_USER_PASSWORD" "$VNC_PASSWORD"

    - name: ngrok is now listening to VNC connections on...
      run: |
        ngrok_url=$(curl --silent http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url' || echo "Error: Unable to retrieve ngrok URL")
        echo "$ngrok_url"

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v2
